---
servers:
    - host: "1.2.3.4:5555"

events:
# If i get a relative path, should I assume it's relative
# to the config, or to the working directory of the process?
    - cmd: "/path/to/script"
      interval: 1 # seconds


